app.deadline: "11:00"

# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  profiles:
    active: @spring.profiles.active@
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      # http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    root: WARN
    com.redfox.restaurantvoting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.cache: TRACE
    liquibase: DEBUG

server:
  servlet:
    context-path: /lunch-manager-reboot
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true  # Enable http encoding support
      force: true
  port: ${PORT:8080}